MISSING DATA

FINDING MISSING DATA

In [17]:
import numpy as np
import pandas as pd

In [18]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
# np.nan is used to reperesent null values ..

In [19]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [20]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [21]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [22]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

REMOVINg missing data

In [23]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [24]:
# removing missing data is based on the rows ..

In [25]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [26]:
df.dropna(thresh = 3) # this will remove rows which have less than 3 non null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

FILLING THE MISSING DATA

In [27]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [28]:
df.fillna(0) # this will fill the missing values with 0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

Filling columns  with different  values

In [32]:
values = {'A': 0, 'B': 1, 'C': 2, 'D': 3}
df.fillna(value = values) # this will fill the missing values with the specified values for each column

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  0.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0